### ISSUE TITLE
Shadowlands update

### ISSUE THREAD

**Issue by infekSK** [darki73/BestInSlotNG#1]
Hi, love the addon.

Will you be updating it for Shadowlands?

**Comment by darki73** [comment]
@infekSK Hello, this addon was a part of our guild website, as i am in the process of rewriting guild website (90% of addon  data generation logic depends on the guild website), it will be released "when it is ready"

**Comment by infekSK** [comment]
Totally understandable.

Hope all goes well with the rewrite!

**Comment by darki73** [comment]
@infekSK Updated with the latest data
